import urllib

#architecture
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/application_structure.md", "architecture/applicationStructure.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/build_process.md", "architecture/buildProcess.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/extention_guide.md", "architecture/extentionGuide.md")

#components
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-fulfillment/v6.1.0/README.md", "components/fulfillmentService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-requisition/v5.1.0/README.md", "components/requisitionService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-auth/v3.1.1/README.md", "components/authService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-referencedata/v9.0.0/README.md", "components/referencedataService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-stockmanagement/v2.0.0/README.md", "components/stockmanagementService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-report/v1.0.0/README.md", "components/reportService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-template-service/v3.2.1/README.md", "components/templateServiceService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-reference-ui/v5.0.4/README.md", "components/referenceUI.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-auth-ui/v6.0.0/README.md", "components/authUI.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-referencedata-ui/v5.2.2/README.md", "components/referencedataUI.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-requisition-ui/v5.2.0/README.md", "components/requisitionUI.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-fulfillment-ui/v5.1.0/README.md", "components/fulfillmentUI.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-stockmanagement-ui/v1.0.1/README.md", "components/stockmanagementUI.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-dev-ui/v6/README.md", "components/devUI.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v5.2.0/README.md", "components/uiComponents.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-layout/v5.0.3/README.md", "components/uiLayout.md")

#conventions
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-template-service/v3.2.1/STYLE-GUIDE.md", "conventions/codeStyleguide.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-template-service/v3.2.1/TESTING.md", "conventions/testing.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-template-service/v3.2.1/ERROR_HANDLING.md", "conventions/errorHandling.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/styleguide.md", "conventions/uiStyleguide.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-template-service/v3.2.1/LICENSE-HEADER.md", "conventions/licenseHeader.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/coding_conventions/index.md", "conventions/uiCodeConventions.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/performance.md", "conventions/uiPerformance.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/coding_conventions/constant.md", "conventions/uiConstant.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/coding_conventions/controller.md", "conventions/uiController.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/coding_conventions/css.md", "conventions/uiCss.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/coding_conventions/directive.md", "conventions/uiDirective.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/coding_conventions/factory.md", "conventions/uiFactory.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/coding_conventions/filter.md", "conventions/uiFilter.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/coding_conventions/interceptor.md", "conventions/uiInterceptor.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/coding_conventions/modal.md", "conventions/uiModal.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/coding_conventions/module.md", "conventions/uiModule.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/coding_conventions/pojo.md", "conventions/uiPojo.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/coding_conventions/route.md", "conventions/uiRoute.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v6/docs/coding_conventions/service.md", "conventions/uiService.md")

# deployment
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.2.1/deploymentTopology.md", "deployment/topology.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.2.1/provision/Provision-single-host.md", "deployment/provisionSingleHost.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.2.1/provision/Provision-swarm-With-ELB.md", "deployment/provisionSwarmWithELB.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.2.1/provision/Provision-swarm-With-Elastic-ip.md", "deployment/provisionSwarmWithElasticIp.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.2.1/provision/RDS-configuration.md", "deployment/rdsConfiguration.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.2.1/deployment/README.md", "deployment/demoAndCiJenkins.md")
