
import urllib

#components
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-fulfillment/v9.0.4/README.md", "components/fulfillmentService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-requisition/v8.3.7/README.md", "components/requisitionService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-auth/v4.3.3/README.md", "components/authService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-auth/v4.4.3//DESIGN.md", "components/authServiceDesign.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-cce/v1.3.2/README.md", "components/cceService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-notification/v4.3.3/README.md", "components/notificationService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-referencedata/v15.2.6/README.md", "components/referencedataService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-stockmanagement/v5.1.9/README.md", "components/stockmanagementService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-report/v1.2.2/README.md", "components/reportService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-hapifhir/v2.0.2/README.md", "components/hapifhirService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-diagnostics/v1.1.2/README.md", "components/diagnosticsService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-template-service/v3.7.0/README.md", "components/templateServiceService.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-reference-ui/v.5.2.7/README.md", "components/referenceUI.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-auth-ui/v6.2.11/README.md", "components/authUI.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-cce-ui/v1.1.4/README.md", "components/cceUI.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-referencedata-ui/v5.6.11/README.md", "components/referencedataUI.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-report-ui/v5.2.11/README.md", "components/reportUI.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-requisition-ui/v7.0.11/README.md", "components/requisitionUI.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-fulfillment-ui/v6.1.4/README.md", "components/fulfillmentUI.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-stockmanagement-ui/v2.1.6/README.md", "components/stockmanagementUI.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v9.0.6/README.md", "components/devUI.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.10/README.md", "components/uiComponents.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.10/docs/index.md", "components/uiOverview.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.10/docs/extension_guide.md", "components/uiExtensionGuide.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-layout/v5.2.5/README.md", "components/uiLayout.md")

#conventions
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-template-service/v3.7.0/STYLE-GUIDE.md", "conventions/codeStyleguide.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-template-service/v3.7.0/TESTING.md", "conventions/testing.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-template-service/v3.7.0/ERROR_HANDLING.md", "conventions/errorHandling.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-template-service/v3.7.0/LICENSE-HEADER.md", "conventions/licenseHeader.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.10/docs/conventions.md", "conventions/uiConventions.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.10/docs/conventions-angularjs.md", "conventions/uiAngularjs.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.10/docs/conventions-javascript.md", "conventions/uiJavascript.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.10/docs/conventions-markup.md", "conventions/uiMarkup.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.10/docs/conventions-testing.md", "conventions/uiTesting.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.10/docs/information-architecture.md", "conventions/uiInformationArchitecture.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.10/docs/performance.md", "conventions/uiPerformance.md")

# deployment
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.16/deploymentTopology.md", "deployment/topology.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.16/provision/Provision-single-host.md", "deployment/provisionSingleHost.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.16/provision/Provision-swarm-With-ELB.md", "deployment/provisionSwarmWithELB.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.16/provision/Provision-swarm-With-Elastic-ip.md", "deployment/provisionSwarmWithElasticIp.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.16/provision/RDS-configuration.md", "deployment/rdsConfiguration.md")
urllib.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.16/deployment/README.md", "deployment/demoAndCiJenkins.md")