import urllib

#components
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-fulfillment/v9.3.0/README.md", "components/fulfillmentService.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-dhis2-integration/v1.1.0/README.md", "components/dhis2IntegrationService.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-buq/v1.1.0/README.md", "components/buqService.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-requisition/v8.5.0/README.md",  "components/requisitionService.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-auth/v4.4.0/README.md", "components/authService.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-auth/v4.4.0/DESIGN.md", "components/authServiceDesign.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-cce/v1.4.0/README.md", "components/cceService.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-notification/v4.4.0/README.md", "components/notificationService.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-referencedata/v15.4.0/README.md", "components/referencedataService.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-stockmanagement/v5.3.0/README.md", "components/stockmanagementService.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-report/v1.5.0/README.md", "components/reportService.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-hapifhir/v2.1.0/README.md", "components/hapifhirService.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-diagnostics/v1.1.4/README.md", "components/diagnosticsService.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-template-service/v3.8.0/README.md", "components/templateServiceService.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-reference-ui/v5.2.12/README.md", "components/referenceUI.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-auth-ui/v6.2.16/README.md", "components/authUI.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-cce-ui/v1.1.8/README.md", "components/cceUI.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-referencedata-ui/v5.6.17/README.md", "components/referencedataUI.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-report-ui/v5.2.15/README.md", "components/reportUI.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-requisition-ui/v7.0.15/README.md", "components/requisitionUI.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-fulfillment-ui/v6.1.7/README.md", "components/fulfillmentUI.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-stockmanagement-ui/v2.1.9/README.md", "components/stockmanagementUI.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/dev-ui/v9.0.8/README.md", "components/devUI.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.14/README.md", "components/uiComponents.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.14/docs/index.md", "components/uiOverview.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.14/docs/extension_guide.md", "components/uiExtensionGuide.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-layout/v5.2.9/README.md", "components/uiLayout.md")

#conventions
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-template-service/v3.8.0/STYLE-GUIDE.md", "conventions/codeStyleguide.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-template-service/v3.8.0/TESTING.md", "conventions/testing.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-template-service/v3.8.0/ERROR_HANDLING.md", "conventions/errorHandling.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-template-service/v3.8.0/LICENSE-HEADER.md", "conventions/licenseHeader.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.14/docs/conventions.md", "conventions/uiConventions.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.14/docs/conventions-angularjs.md", "conventions/uiAngularjs.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.14/docs/conventions-javascript.md", "conventions/uiJavascript.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.14/docs/conventions-markup.md", "conventions/uiMarkup.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.14/docs/conventions-testing.md", "conventions/uiTesting.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.14/docs/information-architecture.md", "conventions/uiInformationArchitecture.md")
urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-ui-components/v7.2.14/docs/performance.md", "conventions/uiPerformance.md")

# deployment
# urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.17.0/deploymentTopology.md", "deployment/topology.md")
# urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.17.0/provision/Provision-single-host.md", "deployment/provisionSingleHost.md")
# urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.17.0/provision/Provision-swarm-With-ELB.md", "deployment/provisionSwarmWithELB.md")
# urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.17.0/provision/Provision-swarm-With-Elastic-ip.md", "deployment/provisionSwarmWithElasticIp.md")
# urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.17.0/provision/RDS-configuration.md", "deployment/rdsConfiguration.md")
# urllib.request.urlretrieve("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/v3.17.0/deployment/README.md", "deployment/demoAndCiJenkins.md")("https://raw.githubusercontent.com/OpenLMIS/openlmis-deployment/master/deployment/README.md", "deployment/demoAndCiJenkins.md")
