#!/bin/bash

set -e

# Create an admin user
flask fab create-admin $@

# Initialize the database
superset db upgrade

#load sample data
superset load_examples

# Create default roles and permissions
superset init
